import os

APP_NAME = "MQ IntelliMesh Intelligence Engine"
APP_VERSION = "0.1.0"
API_PREFIX = "/api"

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BASE_DIR, "data")
UPLOADS_DIR = os.path.join(DATA_DIR, "uploads")
OUTPUTS_DIR = os.path.join(DATA_DIR, "outputs")

SUPPORTED_UPLOAD_EXTENSIONS = {".csv"}
MAX_UPLOAD_SIZE_MB = 50
MAX_UPLOAD_SIZE_BYTES = MAX_UPLOAD_SIZE_MB * 1024 * 1024

QUEUE_MANAGER_TYPES = ["DEDICATED", "SHARED", "HUB", "INTEGRATION"]
CHANNEL_TYPES = ["SDR", "RCVR", "SVRCONN", "CLNTCONN", "XMIT"]
QUEUE_TYPES = ["LOCAL", "REMOTE", "ALIAS", "MODEL", "CLUSTER"]

COMPLEXITY_WEIGHT_CHANNEL_COUNT = 0.30
COMPLEXITY_WEIGHT_ROUTING_DEPTH = 0.25
COMPLEXITY_WEIGHT_SHARED_QM_LOAD = 0.20
COMPLEXITY_WEIGHT_DLQ_COVERAGE = 0.15
COMPLEXITY_WEIGHT_NAMING_COMPLIANCE = 0.10
